const {
  REACT_APP_COURSE_HUB_URL,
  REACT_APP_IPS_URL,
  REACT_APP_ORGANIZATION_URL,
  REACT_APP_FLASHCARD_URL,
  REACT_APP_QUIZ_URL,
  REACT_APP_IMAGE_URL,
  REACT_APP_SIMULATION_URL,
  REACT_APP_NOTES_URL,
  REACT_APP_CART_URL,
  REACT_APP_FLASHCARD_PRODUCT_ID,
  REACT_APP_FLASHCARD_AS_LESSON_PRODUCT_ID,
  REACT_APP_QUIZ_PRODUCT_ID,
  REACT_APP_QUIZ_AS_LESSON_PRODUCT_ID,
  REACT_APP_COURSE_PRODUCT_ID
} = process.env

const BACKEND_SERVICES = {
  authService: REACT_APP_IPS_URL,
  courseHubService: REACT_APP_COURSE_HUB_URL,
  organizationService: REACT_APP_ORGANIZATION_URL,
  flashcardService: REACT_APP_FLASHCARD_URL,
  quizService: REACT_APP_QUIZ_URL,
  imageService: REACT_APP_IMAGE_URL,
  simulationService: REACT_APP_SIMULATION_URL,
  notesService: REACT_APP_NOTES_URL,
  cartService: REACT_APP_CART_URL,
  flashcardProductId: REACT_APP_FLASHCARD_PRODUCT_ID,
  flashcardAsLessonProductId: REACT_APP_FLASHCARD_AS_LESSON_PRODUCT_ID,
  quizProductId: REACT_APP_QUIZ_PRODUCT_ID,
  quizAsLessonProductId: REACT_APP_QUIZ_AS_LESSON_PRODUCT_ID,
  courseProductId: REACT_APP_COURSE_PRODUCT_ID,
}

const PRODUCT_IDS = {

}

export { BACKEND_SERVICES }
